Reading-in the datasets into Pandas dataframes from their Github location:

In [1]:
# call pandas
import pandas as pd # 'pd' is a nickname

gitCloudRepo = 'https://github.com/elenapopic542/Deliverable1/raw/main/'
fileName = "GDPGrowth_Data.csv"

DF1csv = pd.read_csv(gitCloudRepo + fileName)

DF1csv

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.833977,5.635318,-0.709567,2.885166,1.515938,4.917139,4.738331,0.181216,-18.698325,17.225300
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-2.360093,5.112132,2.346033,1.728251,2.418551,...,-1.850848,1.402217,1.182822,0.169095,-0.490755,-0.106816,-0.172927,-0.596607,-5.433164,1.643080
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,8.247144,2.002522,-0.964803,-1.666416,-0.345802,-0.253594,-1.688577,0.932833,-5.364666,-22.965296
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-0.274916,1.592994,4.982990,3.112517,1.774233,...,2.259185,3.256967,3.094595,0.021242,-2.530712,-0.390086,0.269736,0.542605,-3.426405,1.357098
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.536024,1.101887,1.028262,-2.646420,-6.011783,-3.633446,-4.676622,-4.014917,-8.635446,-2.050717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.805676,4.702936,3.653588,7.371867,6.203623,4.038709,3.056665,5.237433,-5.406638,10.999527
262,"Yemen, Rep.",YEM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.526828,1.868808,-2.955389,-29.921761,-11.720018,-7.475113,-1.721735,NaN,NaN,NaN
263,South Africa,ZAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,0.977924,3.061899,4.165498,4.685237,2.892205,...,1.044229,1.099462,-0.172221,-0.757928,-0.309171,0.766942,0.285736,-0.987175,-7.481093,3.870315
264,Zambia,ZMB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-1.787685,-5.541489,0.023361,8.686086,12.972033,...,4.103279,1.676101,1.352928,-0.312861,0.561271,0.331284,0.897347,-1.564237,-5.595733,1.669097
265,Zimbabwe,ZWE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,3.076210,-1.666989,2.985427,-4.143906,1.682986,...,13.654750,0.988283,-0.715190,-0.132760,-1.177893,1.974846,2.909395,-8.177320,-9.670405,6.271613

In [2]:
gitCloudRepo = 'https://github.com/elenapopic542/Deliverable1/raw/main/'
fileName = "GNIpercapita_Data.csv"

DF2csv = pd.read_csv(gitCloudRepo + fileName)

DF2csv

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,24440.000000,25500.000000,25790.000000,26180.000000,26650.000000,27720.000000,29030.000000,30000.000000,24590.000000,29390.000000
1,Africa Eastern and Southern,AFE,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1679.256511,1711.725316,1691.540731,1574.778660,1456.026987,1440.565428,1452.233541,1493.732269,1386.163976,1453.744944
2,Afghanistan,AFG,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,650.000000,680.000000,650.000000,610.000000,570.000000,540.000000,520.000000,530.000000,500.000000,390.000000
3,Africa Western and Central,AFW,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,112.632149,121.002027,126.993255,131.869404,...,1763.846950,1923.711925,2096.815123,2004.978658,1771.335338,1587.397582,1604.628244,1663.335667,1644.359873,1707.394011
4,Angola,AGO,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4060.000000,4650.000000,4800.000000,3880.000000,2450.000000,1980.000000,1870.000000,2040.000000,1740.000000,1710.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3540.000000,3800.000000,3910.000000,3930.000000,3930.000000,3950.000000,4300.000000,4640.000000,4440.000000,5130.000000
262,"Yemen, Rep.",YEM,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1180.000000,1340.000000,1360.000000,1110.000000,1070.000000,1000.000000,840.000000,NaN,NaN,NaN
263,South Africa,ZAF,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,550.000000,580.000000,620.000000,660.000000,...,8320.000000,8050.000000,7340.000000,6550.000000,5960.000000,5950.000000,6390.000000,6730.000000,6090.000000,6530.000000
264,Zambia,ZMB,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,190.000000,190.000000,210.000000,260.000000,...,1660.000000,1720.000000,1760.000000,1540.000000,1340.000000,1270.000000,1400.000000,1390.000000,1130.000000,1030.000000
265,Zimbabwe,ZWE,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,210.000000,210.000000,180.000000,230.000000,...,1120.000000,1200.000000,1210.000000,1220.000000,1200.000000,1170.000000,1550.000000,1450.000000,1460.000000,1530.000000

In [3]:
gitCloudRepo = 'https://github.com/elenapopic542/Deliverable1/raw/main/'
fileName = "Inflation_Data.csv"

DF3csv = pd.read_csv(gitCloudRepo + fileName)
DF3csv

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.627472,-2.372065,0.421441,0.474764,-0.931196,-1.028282,3.626041,4.257462,NaN,NaN
1,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,9.158707,5.750981,5.370290,5.250171,6.571396,6.399343,4.720811,4.120246,6.362961,6.079328
2,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,6.441213,7.385772,4.673996,-0.661709,4.383892,4.975952,0.626149,2.302373,NaN,NaN
3,Africa Western and Central,AFW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.578375,2.439201,1.758052,2.130268,1.494564,1.764635,1.784050,1.758565,2.437609,3.837868
4,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,10.277905,8.777814,7.280387,9.353840,30.698958,29.842578,19.630594,17.079704,22.271564,25.754266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.476738,1.767324,0.428958,-0.536929,0.273169,1.488234,1.053798,2.675992,0.198228,3.353691
262,"Yemen, Rep.",YEM,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,9.885387,10.968442,8.104726,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.288859,2.102374,1.246285,1.33797,2.534973,4.069029,...,5.724658,5.784469,6.129838,4.540642,6.571396,5.184247,4.517165,4.120246,3.210036,4.611672
264,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,6.575900,6.977676,7.806876,10.110593,17.869730,6.577312,7.494572,9.150316,15.732585,22.021234
265,Zimbabwe,ZWE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.725327,1.634950,-0.197785,-2.430968,-1.543670,0.893962,10.618866,255.304991,557.201817,98.546105

Cleaning the data:

Examining the columns present in each dataframe:

In [4]:
DF1csv.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype='object')

In [5]:
DF2csv.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype='object')

In [6]:
DF3csv.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype='object')

In [7]:
#Saving a copy of the original file before making any changes 
#original_DF1csv = DF1csv
#original_DF2csv = DF2csv
#original_DF3csv = DF3csv

In [8]:
#DF1csv = original_DF1csv
#DF2csv = original_DF2csv
#DF3csv = original_DF3csv

Dropping the columns that are not needed for analysis from each of the dataframes:

In [9]:
DF1csv.drop(columns=DF1csv.columns[4:44],inplace=True)
DF1csv

,Country Name,Country Code,Indicator Name,Indicator Code,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,4.918354,2.369193,-2.134006,0.117317,6.318777,-1.379148,...,-1.833977,5.635318,-0.709567,2.885166,1.515938,4.917139,4.738331,0.181216,-18.698325,17.225300
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,0.750996,1.036421,1.265662,0.466080,2.788589,3.361069,...,-1.850848,1.402217,1.182822,0.169095,-0.490755,-0.106816,-0.172927,-0.596607,-5.433164,1.643080
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,0.927029,-2.497255,7.321874,...,8.247144,2.002522,-0.964803,-1.666416,-0.345802,-0.253594,-1.688577,0.932833,-5.364666,-22.965296
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,0.967465,2.352157,6.931811,2.641242,5.051312,2.928476,...,2.259185,3.256967,3.094595,0.021242,-2.530712,-0.390086,0.269736,0.542605,-3.426405,1.357098
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,-0.234946,0.838227,9.937307,-0.466061,7.127077,11.009566,...,4.536024,1.101887,1.028262,-2.646420,-6.011783,-3.633446,-4.676622,-4.014917,-8.635446,-2.050717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.805676,4.702936,3.653588,7.371867,6.203623,4.038709,3.056665,5.237433,-5.406638,10.999527
262,"Yemen, Rep.",YEM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,3.251318,1.012423,1.201096,1.033330,1.241632,2.683287,...,-0.526828,1.868808,-2.955389,-29.921761,-11.720018,-7.475113,-1.721735,NaN,NaN,NaN
263,South Africa,ZAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,3.201510,1.794443,2.760878,2.001994,3.581230,4.286772,...,1.044229,1.099462,-0.172221,-0.757928,-0.309171,0.766942,0.285736,-0.987175,-7.481093,3.870315
264,Zambia,ZMB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,1.062292,2.208315,1.360081,3.691828,3.683416,3.741432,...,4.103279,1.676101,1.352928,-0.312861,0.561271,0.331284,0.897347,-1.564237,-5.595733,1.669097
265,Zimbabwe,ZWE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,-4.027576,0.789791,-9.454025,-17.621841,-6.466319,-6.203725,...,13.654750,0.988283,-0.715190,-0.132760,-1.177893,1.974846,2.909395,-8.177320,-9.670405,6.271613

In [10]:
DF2csv.drop(columns=DF2csv.columns[4:44],inplace=True)
DF2csv

,Country Name,Country Code,Indicator Name,Indicator Code,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,20390.000000,20510.000000,19290.000000,21120.000000,24010.000000,20370.000000,...,24440.000000,25500.000000,25790.000000,26180.000000,26650.000000,27720.000000,29030.000000,30000.000000,24590.000000,29390.000000
1,Africa Eastern and Southern,AFE,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,656.176751,629.894844,615.771592,666.312226,810.760703,1015.829058,...,1679.256511,1711.725316,1691.540731,1574.778660,1456.026987,1440.565428,1452.233541,1493.732269,1386.163976,1453.744944
2,Afghanistan,AFG,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,650.000000,680.000000,650.000000,610.000000,570.000000,540.000000,520.000000,530.000000,500.000000,390.000000
3,Africa Western and Central,AFW,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,452.032442,474.237653,517.338594,578.193287,704.092894,831.636292,...,1763.846950,1923.711925,2096.815123,2004.978658,1771.335338,1587.397582,1604.628244,1663.335667,1644.359873,1707.394011
4,Angola,AGO,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,360.000000,390.000000,590.000000,710.000000,1010.000000,1370.000000,...,4060.000000,4650.000000,4800.000000,3880.000000,2450.000000,1980.000000,1870.000000,2040.000000,1740.000000,1710.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3540.000000,3800.000000,3910.000000,3930.000000,3930.000000,3950.000000,4300.000000,4640.000000,4440.000000,5130.000000
262,"Yemen, Rep.",YEM,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,400.000000,450.000000,490.000000,510.000000,580.000000,660.000000,...,1180.000000,1340.000000,1360.000000,1110.000000,1070.000000,1000.000000,840.000000,NaN,NaN,NaN
263,South Africa,ZAF,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,3280.000000,3080.000000,2890.000000,3180.000000,4070.000000,5480.000000,...,8320.000000,8050.000000,7340.000000,6550.000000,5960.000000,5950.000000,6390.000000,6730.000000,6090.000000,6530.000000
264,Zambia,ZMB,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,350.000000,360.000000,380.000000,420.000000,480.000000,580.000000,...,1660.000000,1720.000000,1760.000000,1540.000000,1340.000000,1270.000000,1400.000000,1390.000000,1130.000000,1030.000000
265,Zimbabwe,ZWE,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,360.000000,390.000000,370.000000,340.000000,320.000000,330.000000,...,1120.000000,1200.000000,1210.000000,1220.000000,1200.000000,1170.000000,1550.000000,1450.000000,1460.000000,1530.000000

In [11]:
DF3csv.drop(columns=DF3csv.columns[4:44],inplace=True)
DF3csv

,Country Name,Country Code,Indicator Name,Indicator Code,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,4.044021,2.883604,3.315247,3.656365,2.529129,3.397787,...,0.627472,-2.372065,0.421441,0.474764,-0.931196,-1.028282,3.626041,4.257462,NaN,NaN
1,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,8.601485,5.840354,8.763754,7.449700,5.023421,8.558038,...,9.158707,5.750981,5.370290,5.250171,6.571396,6.399343,4.720811,4.120246,6.362961,6.079328
2,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,12.686269,...,6.441213,7.385772,4.673996,-0.661709,4.383892,4.975952,0.626149,2.302373,NaN,NaN
3,Africa Western and Central,AFW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2.530775,4.361529,3.188693,1.760904,0.694336,5.631634,...,4.578375,2.439201,1.758052,2.130268,1.494564,1.764635,1.784050,1.758565,2.437609,3.837868
4,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,324.996872,152.561023,108.897436,98.224144,43.542107,22.953514,...,10.277905,8.777814,7.280387,9.353840,30.698958,29.842578,19.630594,17.079704,22.271564,25.754266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,-1.084813,-1.064727,-1.385189,...,2.476738,1.767324,0.428958,-0.536929,0.273169,1.488234,1.053798,2.675992,0.198228,3.353691
262,"Yemen, Rep.",YEM,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,4.590000,11.911591,12.238534,10.832361,12.515095,11.811264,...,9.885387,10.968442,8.104726,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,5.338951,5.701900,9.494711,5.679418,-0.692030,2.062846,...,5.724658,5.784469,6.129838,4.540642,6.571396,5.184247,4.517165,4.120246,3.210036,4.611672
264,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,26.030412,21.393782,22.233345,21.401578,17.967789,18.324440,...,6.575900,6.977676,7.806876,10.110593,17.869730,6.577312,7.494572,9.150316,15.732585,22.021234
265,Zimbabwe,ZWE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.725327,1.634950,-0.197785,-2.430968,-1.543670,0.893962,10.618866,255.304991,557.201817,98.546105

Checking the names of the columns:

In [12]:
DF1csv.columns.to_list()

['Country Name',
 'Country Code',
 'Indicator Name',
 'Indicator Code',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021']

In [13]:
DF2csv.columns.to_list()

['Country Name',
 'Country Code',
 'Indicator Name',
 'Indicator Code',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021']

In [14]:
DF3csv.columns.to_list()

['Country Name',
 'Country Code',
 'Indicator Name',
 'Indicator Code',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021']

Eliminating spaces in column names:

In [15]:
DF1csv.columns.str.replace(" ","",regex=True)

Index(['CountryName', 'CountryCode', 'IndicatorName', 'IndicatorCode', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021'],
      dtype='object')

In [16]:
DF2csv.columns.str.replace(" ","",regex=True)

Index(['CountryName', 'CountryCode', 'IndicatorName', 'IndicatorCode', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021'],
      dtype='object')

In [17]:
DF3csv.columns.str.replace(" ","",regex=True)

Index(['CountryName', 'CountryCode', 'IndicatorName', 'IndicatorCode', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021'],
      dtype='object')

In [18]:
DF1csv.columns = DF1csv.columns.str.replace(" ","",regex=True)

In [19]:
DF2csv.columns = DF2csv.columns.str.replace(" ","",regex=True)

In [20]:
DF3csv.columns = DF3csv.columns.str.replace(" ","",regex=True)

In [21]:
DF1csv.columns.to_list()

['CountryName',
 'CountryCode',
 'IndicatorName',
 'IndicatorCode',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021']

In [22]:
DF2csv.columns.to_list()

['CountryName',
 'CountryCode',
 'IndicatorName',
 'IndicatorCode',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021']

In [23]:
DF3csv.columns.to_list()

['CountryName',
 'CountryCode',
 'IndicatorName',
 'IndicatorCode',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021']

Eliminating spaces before the first and last characters in text entry fields:

In [24]:
DF1csv.CountryName.str.strip()

0                            Aruba
1      Africa Eastern and Southern
2                      Afghanistan
3       Africa Western and Central
4                           Angola
                  ...
261                         Kosovo
262                    Yemen, Rep.
263                   South Africa
264                         Zambia
265                       Zimbabwe
Name: CountryName, Length: 266, dtype: object

In [25]:
DF1csv.IndicatorName.str.strip()

0      GDP per capita growth (annual %)
1      GDP per capita growth (annual %)
2      GDP per capita growth (annual %)
3      GDP per capita growth (annual %)
4      GDP per capita growth (annual %)
                     ...
261    GDP per capita growth (annual %)
262    GDP per capita growth (annual %)
263    GDP per capita growth (annual %)
264    GDP per capita growth (annual %)
265    GDP per capita growth (annual %)
Name: IndicatorName, Length: 266, dtype: object

In [26]:
DF2csv.CountryName.str.strip()

0                            Aruba
1      Africa Eastern and Southern
2                      Afghanistan
3       Africa Western and Central
4                           Angola
                  ...
261                         Kosovo
262                    Yemen, Rep.
263                   South Africa
264                         Zambia
265                       Zimbabwe
Name: CountryName, Length: 266, dtype: object

In [27]:
DF2csv.IndicatorName.str.strip()

0      GNI per capita, Atlas method (current US$)
1      GNI per capita, Atlas method (current US$)
2      GNI per capita, Atlas method (current US$)
3      GNI per capita, Atlas method (current US$)
4      GNI per capita, Atlas method (current US$)
                          ...
261    GNI per capita, Atlas method (current US$)
262    GNI per capita, Atlas method (current US$)
263    GNI per capita, Atlas method (current US$)
264    GNI per capita, Atlas method (current US$)
265    GNI per capita, Atlas method (current US$)
Name: IndicatorName, Length: 266, dtype: object

In [28]:
DF3csv.CountryName.str.strip()

0                            Aruba
1      Africa Eastern and Southern
2                      Afghanistan
3       Africa Western and Central
4                           Angola
                  ...
261                         Kosovo
262                    Yemen, Rep.
263                   South Africa
264                         Zambia
265                       Zimbabwe
Name: CountryName, Length: 266, dtype: object

In [29]:
DF3csv.IndicatorName.str.strip()

0      Inflation, consumer prices (annual %)
1      Inflation, consumer prices (annual %)
2      Inflation, consumer prices (annual %)
3      Inflation, consumer prices (annual %)
4      Inflation, consumer prices (annual %)
                       ...
261    Inflation, consumer prices (annual %)
262    Inflation, consumer prices (annual %)
263    Inflation, consumer prices (annual %)
264    Inflation, consumer prices (annual %)
265    Inflation, consumer prices (annual %)
Name: IndicatorName, Length: 266, dtype: object

Examining the types of data in each dataframe:

In [30]:
DF1csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    266 non-null    object
 1   CountryCode    266 non-null    object
 2   IndicatorName  266 non-null    object
 3   IndicatorCode  266 non-null    object
 4   2000           239 non-null    float64
 5   2001           245 non-null    float64
 6   2002           246 non-null    float64
 7   2003           251 non-null    float64
 8   2004           251 non-null    float64
 9   2005           252 non-null    float64
 10  2006           252 non-null    float64
 11  2007           253 non-null    float64
 12  2008           252 non-null    float64
 13  2009           254 non-null    float64
 14  2010           254 non-null    float64
 15  2011           254 non-null    float64
 16  2012           254 non-null    float64
 17  2013           254 non-null    float64
 18  2014           256 non-null    float64
 19  2015           255 non-null    float64
 20  2016           254 non-null    float64
 21  2017           254 non-null    float64
 22  2018           254 non-null    float64
 23  2019           252 non-null    float64
 24  2020           249 non-null    float64
 25  2021           244 non-null    float64
dtypes: float64(22), object(4)
memory usage: 54.2+ KB

In [31]:
DF2csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    266 non-null    object
 1   CountryCode    266 non-null    object
 2   IndicatorName  266 non-null    object
 3   IndicatorCode  266 non-null    object
 4   2000           230 non-null    float64
 5   2001           229 non-null    float64
 6   2002           238 non-null    float64
 7   2003           239 non-null    float64
 8   2004           239 non-null    float64
 9   2005           239 non-null    float64
 10  2006           240 non-null    float64
 11  2007           240 non-null    float64
 12  2008           238 non-null    float64
 13  2009           239 non-null    float64
 14  2010           241 non-null    float64
 15  2011           242 non-null    float64
 16  2012           242 non-null    float64
 17  2013           244 non-null    float64
 18  2014           245 non-null    float64
 19  2015           246 non-null    float64
 20  2016           245 non-null    float64
 21  2017           246 non-null    float64
 22  2018           246 non-null    float64
 23  2019           245 non-null    float64
 24  2020           240 non-null    float64
 25  2021           232 non-null    float64
dtypes: float64(22), object(4)
memory usage: 54.2+ KB

In [32]:
DF3csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    266 non-null    object
 1   CountryCode    266 non-null    object
 2   IndicatorName  266 non-null    object
 3   IndicatorCode  266 non-null    object
 4   2000           211 non-null    float64
 5   2001           216 non-null    float64
 6   2002           218 non-null    float64
 7   2003           221 non-null    float64
 8   2004           222 non-null    float64
 9   2005           225 non-null    float64
 10  2006           228 non-null    float64
 11  2007           230 non-null    float64
 12  2008           231 non-null    float64
 13  2009           234 non-null    float64
 14  2010           236 non-null    float64
 15  2011           240 non-null    float64
 16  2012           239 non-null    float64
 17  2013           237 non-null    float64
 18  2014           235 non-null    float64
 19  2015           234 non-null    float64
 20  2016           234 non-null    float64
 21  2017           229 non-null    float64
 22  2018           226 non-null    float64
 23  2019           224 non-null    float64
 24  2020           217 non-null    float64
 25  2021           205 non-null    float64
dtypes: float64(22), object(4)
memory usage: 54.2+ KB

Checking unique values:

In [33]:
DF1csv['CountryName'].unique()

array(['Aruba', 'Africa Eastern and Southern', 'Afghanistan',
       'Africa Western and Central', 'Angola', 'Albania', 'Andorra',
       'Arab World', 'United Arab Emirates', 'Argentina', 'Armenia',
       'American Samoa', 'Antigua and Barbuda', 'Australia', 'Austria',
       'Azerbaijan', 'Burundi', 'Belgium', 'Benin', 'Burkina Faso',
       'Bangladesh', 'Bulgaria', 'Bahrain', 'Bahamas, The',
       'Bosnia and Herzegovina', 'Belarus', 'Belize', 'Bermuda',
       'Bolivia', 'Brazil', 'Barbados', 'Brunei Darussalam', 'Bhutan',
       'Botswana', 'Central African Republic', 'Canada',
       'Central Europe and the Baltics', 'Switzerland', 'Channel Islands',
       'Chile', 'China', "Cote d'Ivoire", 'Cameroon', 'Congo, Dem. Rep.',
       'Congo, Rep.', 'Colombia', 'Comoros', 'Cabo Verde', 'Costa Rica',
       'Caribbean small states', 'Cuba', 'Curacao', 'Cayman Islands',
       'Cyprus', 'Czechia', 'Germany', 'Djibouti', 'Dominica', 'Denmark',
       'Dominican Republic', 'Algeria',
       'East Asia & Pacific (excluding high income)',
       'Early-demographic dividend', 'East Asia & Pacific',
       'Europe & Central Asia (excluding high income)',
       'Europe & Central Asia', 'Ecuador', 'Egypt, Arab Rep.',
       'Euro area', 'Eritrea', 'Spain', 'Estonia', 'Ethiopia',
       'European Union', 'Fragile and conflict affected situations',
       'Finland', 'Fiji', 'France', 'Faroe Islands',
       'Micronesia, Fed. Sts.', 'Gabon', 'United Kingdom', 'Georgia',
       'Ghana', 'Gibraltar', 'Guinea', 'Gambia, The', 'Guinea-Bissau',
       'Equatorial Guinea', 'Greece', 'Grenada', 'Greenland', 'Guatemala',
       'Guam', 'Guyana', 'High income', 'Hong Kong SAR, China',
       'Honduras', 'Heavily indebted poor countries (HIPC)', 'Croatia',
       'Haiti', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA total',
       'IDA blend', 'Indonesia', 'IDA only', 'Isle of Man', 'India',
       'Not classified', 'Ireland', 'Iran, Islamic Rep.', 'Iraq',
       'Iceland', 'Israel', 'Italy', 'Jamaica', 'Jordan', 'Japan',
       'Kazakhstan', 'Kenya', 'Kyrgyz Republic', 'Cambodia', 'Kiribati',
       'St. Kitts and Nevis', 'Korea, Rep.', 'Kuwait',
       'Latin America & Caribbean (excluding high income)', 'Lao PDR',
       'Lebanon', 'Liberia', 'Libya', 'St. Lucia',
       'Latin America & Caribbean',
       'Least developed countries: UN classification', 'Low income',
       'Liechtenstein', 'Sri Lanka', 'Lower middle income',
       'Low & middle income', 'Lesotho', 'Late-demographic dividend',
       'Lithuania', 'Luxembourg', 'Latvia', 'Macao SAR, China',
       'St. Martin (French part)', 'Morocco', 'Monaco', 'Moldova',
       'Madagascar', 'Maldives', 'Middle East & North Africa', 'Mexico',
       'Marshall Islands', 'Middle income', 'North Macedonia', 'Mali',
       'Malta', 'Myanmar',
       'Middle East & North Africa (excluding high income)', 'Montenegro',
       'Mongolia', 'Northern Mariana Islands', 'Mozambique', 'Mauritania',
       'Mauritius', 'Malawi', 'Malaysia', 'North America', 'Namibia',
       'New Caledonia', 'Niger', 'Nigeria', 'Nicaragua', 'Netherlands',
       'Norway', 'Nepal', 'Nauru', 'New Zealand', 'OECD members', 'Oman',
       'Other small states', 'Pakistan', 'Panama', 'Peru', 'Philippines',
       'Palau', 'Papua New Guinea', 'Poland', 'Pre-demographic dividend',
       'Puerto Rico', "Korea, Dem. People's Rep.", 'Portugal', 'Paraguay',
       'West Bank and Gaza', 'Pacific island small states',
       'Post-demographic dividend', 'French Polynesia', 'Qatar',
       'Romania', 'Russian Federation', 'Rwanda', 'South Asia',
       'Saudi Arabia', 'Sudan', 'Senegal', 'Singapore', 'Solomon Islands',
       'Sierra Leone', 'El Salvador', 'San Marino', 'Somalia', 'Serbia',
       'Sub-Saharan Africa (excluding high income)', 'South Sudan',
       'Sub-Saharan Africa', 'Small states', 'Sao Tome and Principe',
       'Suriname', 'Slovak Republic', 'Slovenia', 'Sweden', 'Eswatini',
       'Sint Maarten (Dutch part)', 'Seychelles', 'Syrian Arab Republic',
       'Turks and Caicos Islands', 'Chad',
       'East Asia & Pacific (IDA & IBRD countries)',
       'Europe & Central Asia (IDA & IBRD countries)', 'Togo', 'Thailand',
       'Tajikistan', 'Turkmenistan',
       'Latin America & the Caribbean (IDA & IBRD countries)',
       'Timor-Leste', 'Middle East & North Africa (IDA & IBRD countries)',
       'Tonga', 'South Asia (IDA & IBRD)',
       'Sub-Saharan Africa (IDA & IBRD countries)', 'Trinidad and Tobago',
       'Tunisia', 'Turkiye', 'Tuvalu', 'Tanzania', 'Uganda', 'Ukraine',
       'Upper middle income', 'Uruguay', 'United States', 'Uzbekistan',
       'St. Vincent and the Grenadines', 'Venezuela, RB',
       'British Virgin Islands', 'Virgin Islands (U.S.)', 'Vietnam',
       'Vanuatu', 'World', 'Samoa', 'Kosovo', 'Yemen, Rep.',
       'South Africa', 'Zambia', 'Zimbabwe'], dtype=object)

In [43]:
#Dropping the "Not Classified" observation:
DF1csv = DF1csv[DF1csv["CountryName"].str.contains("Not classified") == False]
DF2csv = DF2csv[DF1csv["CountryName"].str.contains("Not classified") == False]
DF3csv[DF3csv["CountryName"].str.contains("Not classified") == False]

/var/folders/jb/lq0t13x96m323srfn512c7cm0000gn/T/ipykernel_22863/1352920214.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  DF2csv = DF2csv[DF1csv["CountryName"].str.contains("Not classified") == False]

,CountryName,CountryCode,IndicatorName,IndicatorCode,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,8.601485,5.840354,8.763754,7.449700,5.023421,8.558038,...,9.158707,5.750981,5.370290,5.250171,6.571396,6.399343,4.720811,4.120246,6.362961,6.079328
3,Africa Western and Central,AFW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2.530775,4.361529,3.188693,1.760904,0.694336,5.631634,...,4.578375,2.439201,1.758052,2.130268,1.494564,1.764635,1.784050,1.758565,2.437609,3.837868
4,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,324.996872,152.561023,108.897436,98.224144,43.542107,22.953514,...,10.277905,8.777814,7.280387,9.353840,30.698958,29.842578,19.630594,17.079704,22.271564,25.754266
5,Albania,ALB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.050018,3.107588,7.770526,0.484003,2.280019,2.366582,...,2.031593,1.937621,1.625865,3.501208,-0.367317,2.060598,2.028060,1.411091,1.620887,2.041472
7,Arab World,ARB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.853790,1.772204,1.832994,2.712592,3.632280,3.493685,...,4.611844,3.238108,2.773516,1.814077,2.068840,1.966826,2.458142,1.091848,1.777408,3.423629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,Vanuatu,VUT,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2.537688,3.577555,1.963568,3.016241,1.418919,1.199201,...,1.347404,1.458934,0.798864,2.483269,0.842069,3.084526,2.330964,2.762520,5.329351,2.343284
259,World,WLD,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,3.433516,3.836573,2.907999,3.025045,3.517999,4.107251,...,3.725327,2.621050,2.346269,1.434318,1.550016,2.192010,2.438737,2.186902,1.920968,3.495058
260,Samoa,WSM,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.966782,3.838285,8.050314,0.115830,16.313151,1.856764,...,2.049019,0.610086,-0.406816,0.724470,1.304719,1.749897,4.197459,0.982327,-1.568912,3.133205
263,South Africa,ZAF,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,5.338951,5.701900,9.494711,5.679418,-0.692030,2.062846,...,5.724658,5.784469,6.129838,4.540642,6.571396,5.184247,4.517165,4.120246,3.210036,4.611672
264,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,26.030412,21.393782,22.233345,21.401578,17.967789,18.324440,...,6.575900,6.977676,7.806876,10.110593,17.869730,6.577312,7.494572,9.150316,15.732585,22.021234

Checking which cells have missing values:

In [35]:
DF1csv[DF1csv.isna().any(axis=1)]

,CountryName,CountryCode,IndicatorName,IndicatorCode,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,0.927029,-2.497255,7.321874,...,8.247144,2.002522,-0.964803,-1.666416,-0.345802,-0.253594,-1.688577,0.932833,-5.364666,-22.965296
11,American Samoa,ASM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,1.376761,0.958705,0.238921,...,-3.231911,-1.219502,3.279022,4.854442,0.113644,-5.135340,4.874061,1.831714,7.640301,0.648378
38,Channel Islands,CHI,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,5.466132,-2.010643,-2.382830,-3.968233,-0.578063,0.554006,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Curacao,CUW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,3.007946,0.274293,-1.758682,-1.505340,-1.858440,...,-0.891840,-1.929814,-2.523882,-1.023791,-1.918515,-2.045725,-1.651731,-2.208758,-17.125672,5.995960
52,Cayman Islands,CYM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.205742,-1.072927,0.332870,0.550605,1.011165,1.032113,2.173373,1.909769,-7.333185,0.606173
56,Djibouti,DJI,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.185263,5.691156,5.343522,3.737482,3.093088,3.894529,-0.298339,3.352384
69,Eritrea,ERI,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,-4.615492,5.705290,-0.451653,-6.543073,-2.577857,0.089826,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Faroe Islands,FRO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Gibraltar,GIB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,Greenland,GRL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,6.911025,0.999464,-1.424258,4.143054,6.632324,4.943236,...,1.536977,-0.726862,5.091927,-2.214919,4.547809,0.079446,0.888889,1.903880,0.103713,NaN
93,Guam,GUM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,0.371784,6.091850,3.373803,...,1.677786,1.287431,1.495953,0.564587,-0.037012,0.734522,-0.834569,2.628136,-11.710001,0.285940
108,Isle of Man,IMN,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,4.054161,4.246639,5.119877,4.971811,4.213214,4.915875,...,7.319025,4.381825,5.466146,-0.024726,7.135585,4.525979,1.975486,0.066136,NaN,NaN
127,Kuwait,KWT,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,1.584750,-2.643265,0.212209,14.303300,7.579611,6.555497,...,-1.252963,-5.836804,-2.573422,-3.194174,-0.617016,-6.486674,-2.128276,-3.326746,-7.169357,NaN
131,Liberia,LBR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-0.062902,1.086354,-30.701540,1.394829,0.643907,...,4.239483,6.341041,-1.350448,-2.033030,-3.516456,0.521366,-0.761555,-4.343456,-4.933202,2.847282
137,Liechtenstein,LIE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,1.935645,-1.774063,-1.925417,-2.823011,2.137955,3.910153,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,St. Martin (French part),MAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,Northern Mariana Islands,MNP,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,3.757283,0.595458,-9.069361,...,1.120796,3.110271,4.750104,4.069819,30.174901,24.151649,-18.663587,-10.347722,NaN,NaN
172,New Caledonia,NCL,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,0.177143,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,Nauru,NRU,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,-2.870535,...,9.646905,27.558845,23.716579,1.432143,1.289362,-7.723839,3.944289,-1.714474,-0.353648,-0.090121
183,Other small states,OSS,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,2.275154,2.724902,2.729012,7.146041,3.656498,...,1.359383,1.459292,1.404398,0.650267,0.643236,-0.738445,0.423527,0.540864,-5.939492,2.802724
188,Palau,PLW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,5.892553,3.459381,-3.404498,4.713813,4.358278,...,3.338247,-2.622222,6.347622,7.551150,-0.206755,-4.191742,-0.043197,0.104576,-9.390425,-13.583370
193,"Korea, Dem. People's Rep.",PRK,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,Qatar,QAT,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-1.136390,2.019063,-1.176818,14.710639,-1.470185,...,-0.847554,-1.177192,-3.178366,-3.928099,-4.107862,-5.732610,-0.776739,-0.679178,-2.005009,4.317369
212,San Marino,SMR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,0.583244,3.600801,-1.963040,1.577672,2.780789,0.984602,...,-8.831708,-1.240035,-1.011663,1.739979,1.545833,-0.395286,1.196757,1.999987,-6.178501,NaN
213,Somalia,SOM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.094889,11.249431,4.515796,-1.584689,3.715161,3.622518,-0.954716,0.826442
216,South Sudan,SSD,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-48.392454,9.010103,2.384899,-10.642074,NaN,NaN,NaN,NaN,NaN,NaN
218,Small states,SST,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,1.961619,2.697252,3.178379,6.080275,3.435052,...,1.595224,1.420193,1.528307,0.603728,0.257112,-0.626222,0.486950,0.580262,-6.610659,2.947632
219,Sao Tome and Principe,STP,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,0.888640,5.530033,0.954335,3.988166,...,1.034866,2.741293,4.532199,2.037437,2.379076,2.149747,1.333948,0.660539,1.119960,-0.161398
225,Sint Maarten (Dutch part),SXM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.136463,-4.136776,-1.325378,-2.547997,-2.376527,-7.204622,-7.333129,NaN,NaN,NaN
227,Syrian Arab Republic,SYR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,-1.833603,-1.491552,1.313732,4.481402,4.108900,3.359879,...,-25.931192,-22.495212,-3.949253,0.146193,-5.216547,-0.823278,-0.442850,-2.630992,-6.994245,NaN
228,Turks and Caicos Islands,TCA,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.877104,-3.481133,4.388947,6.583542,2.461529,-6.400987,1.428470,1.429890,-28.760645,0.203473
235,Turkmenistan,TKM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,3.898200,2.858929,-1.105636,1.966410,3.675777,11.507496,...,9.108041,8.190014,8.292781,4.592544,4.351812,4.718773,4.507070,4.688624,NaN,NaN
237,Timor-Leste,TLS,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,14.440139,-8.407210,-3.985315,-1.644957,0.509519,...,2.582021,0.983314,2.419697,0.974984,1.800103,-4.513693,-2.154900,21.720270,29.929978,3.621770
254,"Venezuela, RB",VEN,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,1.731145,1.513898,-10.477425,-9.369276,16.280063,8.490127,...,4.284534,0.094579,-5.025111,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,British Virgin Islands,VGB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,Virgin Islands (U.S.),VIR,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,-0.392409,3.323031,3.497714,...,-14.732185,-6.157647,-1.629762,-0.267922,1.786071,-0.517854,2.171426,3.097667,-1.798091,NaN
261,Kosovo,XKX,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.805676,4.702936,3.653588,7.371867,6.203623,4.038709,3.056665,5.237433,-5.406638,10.999527
262,"Yemen, Rep.",YEM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,3.251318,1.012423,1.201096,1.033330,1.241632,2.683287,...,-0.526828,1.868808,-2.955389,-29.921761,-11.720018,-7.475113,-1.721735,NaN,NaN,NaN

In [36]:
DF2csv[DF2csv.isna().any(axis=1)]

,CountryName,CountryCode,IndicatorName,IndicatorCode,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
2,Afghanistan,AFG,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,650.000000,680.000000,650.000000,610.000000,570.000000,540.000000,520.000000,530.000000,500.000000,390.00000
6,Andorra,AND,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46530.000000,NaN,NaN
7,Arab World,ARB,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2571.307942,2679.003479,2640.880791,2818.017999,3270.597121,3724.377540,...,6875.577972,7270.981782,7347.761356,6880.572581,6458.664325,6022.643413,6170.040736,6327.986897,5874.425692,NaN
8,United Arab Emirates,ARE,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,30050.000000,30570.000000,29620.000000,31910.000000,36840.000000,40190.000000,...,41810.000000,45850.000000,47420.000000,46270.000000,44460.000000,42090.000000,44350.000000,46210.000000,41770.000000,NaN
11,American Samoa,ASM,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Bahrain,BHR,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,10220.000000,10980.000000,11850.000000,12950.000000,14510.000000,16310.000000,...,23360.000000,24790.000000,24530.000000,22740.000000,21820.000000,21790.000000,23210.000000,24420.000000,22950.000000,NaN
27,Bermuda,BMU,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,100100.000000,101760.000000,99920.000000,101120.000000,103620.000000,112940.000000,117000.000000,117280.000000,111800.000000,122470.00000
38,Channel Islands,CHI,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,43430.000000,42330.000000,41390.000000,43840.000000,50740.000000,56620.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Cuba,CUB,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,2620.000000,2760.000000,2830.000000,3100.000000,3500.000000,3970.000000,...,6080.000000,6620.000000,6820.000000,7220.000000,7480.000000,7950.000000,8630.000000,8920.000000,NaN,NaN
51,Curacao,CUW,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,19890.000000,19760.000000,19520.000000,19030.000000,18960.000000,19430.000000,19700.000000,16690.000000,18430.00000
52,Cayman Islands,CYM,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,51400.000000,45330.000000,43860.000000,44970.000000,48480.000000,52670.000000,58820.000000,65680.000000,61880.000000,NaN
56,Djibouti,DJI,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2310.000000,2400.000000,2480.000000,2640.000000,2820.000000,2830.000000,3080.00000
69,Eritrea,ERI,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,290.000000,300.000000,290.000000,290.000000,330.000000,390.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Faroe Islands,FRO,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Gibraltar,GIB,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,Greece,GRC,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,23180.000000,22430.000000,22010.000000,20190.000000,18640.000000,17960.000000,19080.000000,19690.000000,17960.000000,20000.00000
91,Greenland,GRL,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,20290.000000,19390.000000,18760.000000,20440.000000,25730.000000,30920.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,Guam,GUM,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,Isle of Man,IMN,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,22280.000000,22870.000000,24130.000000,28120.000000,34540.000000,40030.000000,...,82400.000000,87680.000000,88570.000000,83630.000000,78710.000000,78840.000000,83960.000000,84580.000000,NaN,NaN
110,Not classified,INX,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,Kuwait,KWT,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,19000.000000,19710.000000,19760.000000,23240.000000,29130.000000,35760.000000,...,49020.000000,51310.000000,50050.000000,41040.000000,34540.000000,30880.000000,32300.000000,34290.000000,NaN,NaN
131,Liberia,LBR,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,250.000000,180.000000,210.000000,250.000000,...,540.000000,620.000000,630.000000,630.000000,620.000000,630.000000,620.000000,610.000000,600.000000,630.00000
132,Libya,LBY,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,5290.000000,5240.000000,5160.000000,6810.000000,...,13810.000000,12120.000000,9460.000000,8690.000000,7980.000000,10220.000000,11520.000000,10530.000000,7890.000000,8700.00000
137,Liechtenstein,LIE,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,79240.000000,68600.000000,65420.000000,68800.000000,79030.000000,93020.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,St. Martin (French part),MAF,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,Monaco,MCO,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,Middle East & North Africa,MEA,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,3019.211653,3120.235430,3087.228825,3307.396323,3793.357098,4303.889700,...,8191.562500,8568.541133,8551.241962,7889.214203,7494.506643,7110.940633,7305.999997,7393.079916,6864.243133,NaN
162,Montenegro,MNE,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,1970.000000,2440.000000,3100.000000,3660.000000,...,7000.000000,7330.000000,7320.000000,7260.000000,7090.000000,7410.000000,8450.000000,9140.000000,7900.000000,9340.00000
164,Northern Mariana Islands,MNP,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,New Caledonia,NCL,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,13210.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,Nauru,NRU,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8610.000000,12410.000000,14030.000000,12690.000000,11650.000000,11150.000000,12980.000000,14400.000000,15240.000000,16920.00000
183,Other small states,OSS,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,4107.271822,4601.874783,5583.781171,6714.331575,...,13579.200420,14620.070740,14774.924740,13724.905110,12584.973250,11906.198990,12651.052030,13290.580520,12225.273870,12741.34361
188,Palau,PLW,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,9100.000000,8770.000000,9400.000000,10320.000000,...,12540.000000,12720.000000,14020.000000,15750.000000,16620.000000,16430.000000,17410.000000,17150.000000,14640.000000,12790.00000
193,"Korea, Dem. People's Rep.",PRK,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,French Polynesia,PYF,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,18560.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,Qatar,QAT,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,25520.000000,27950.000000,35010.000000,39010.000000,...,83990.000000,91130.000000,89830.000000,78040.000000,66030.000000,57190.000000,59150.000000,61720.000000,58370.000000,62310.00000
205,Saudi Arabia,SAU,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,7810.000000,8180.000000,8070.000000,9200.000000,10800.000000,12350.000000,...,22740.000000,24280.000000,24590.000000,22970.000000,20980.000000,19350.000000,21040.000000,22210.000000,21540.000000,NaN
212,San Marino,SMR,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,39740.000000,42250.000000,44390.000000,41450.000000,NaN
213,Somalia,SOM,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,400.000000,400.000000,380.000000,390.000000,410.000000,410.000000,430.00000
216,South Sudan,SSD,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,800.000000,1090.000000,1170.000000,1040.000000,NaN,NaN,NaN,NaN,NaN,NaN
218,Small states,SST,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,4185.626388,4647.916644,5510.053470,6465.437554,...,12183.512490,13084.225280,13246.339100,12460.944530,11501.984210,10992.880950,11622.964730,12187.683770,11139.838500,11665.10962
219,Sao Tome and Principe,STP,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,600.000000,690.000000,800.000000,...,1220.000000,1420.000000,1620.000000,1640.000000,1680.000000,1690.000000,1860.000000,1960.000000,2100.000000,2260.00000
225,Sint Maarten (Dutch part),SXM,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,27540.000000,28670.000000,29560.000000,30890.000000,28210.000000,27510.000000,NaN,NaN,NaN
227,Syrian Arab Republic,SYR,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,4100.000000,4390.000000,4660.000000,5090.000000,5750.000000,6330.000000,...,2650.000000,1280.000000,1080.000000,910.000000,760.000000,730.000000,810.000000,970.000000,760.000000,NaN
228,Turks and Caicos Islands,TCA,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,23530.000000,25140.000000,26100.000000,24400.000000,25730.000000,26710.000000,19610.000000,21410.00000
235,Turkmenistan,TKM,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,590.000000,640.000000,730.000000,960.000000,1270.000000,1550.000000,...,5370.000000,6280.000000,6950.000000,6790.000000,6590.000000,6160.000000,6500.000000,6970.000000,NaN,NaN
237,Timor-Leste,TLS,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,770.000000,680.000000,800.000000,950.000000,...,3560.000000,3190.000000,2690.000000,2180.000000,1740.000000,1800.000000,1820.000000,2110.000000,2100.000000,1140.00000
245,Tuvalu,TUV,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,2700.000000,3430.000000,2620.000000,3390.000000,3760.000000,...,4480.000000,5650.000000,4790.000000,5690.000000,5490.000000,5320.000000,6160.000000,6640.000000,6750.000000,7200.00000
254,"Venezuela, RB",VEN,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,4080.000000,4560.000000,3950.000000,3460.000000,4070.000000,4930.000000,...,12660.000000,11950.000000,13010.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,British Virgin Islands,VGB,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,Virgin Islands (U.S.),VIR,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,Samoa,WSM,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,1410.000000,1550.000000,1830.000000,2220.000000,...,3560.000000,3720.000000,3790.000000,3930.000000,4080.000000,4050.000000,4060.000000,4230.000000,4000.000000,3810.00000
261,Kosovo,XKX,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3540.000000,3800.000000,3910.000000,3930.000000,3930.000000,3950.000000,4300.000000,4640.000000,4440.000000,5130.00000
262,"Yemen, Rep.",YEM,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,400.000000,450.000000,490.000000,510.000000,580.000000,660.000000,...,1180.000000,1340.000000,1360.000000,1110.000000,1070.000000,1000.000000,840.000000,NaN,NaN,NaN

In [37]:
DF3csv[DF3csv.isna().any(axis=1)]

,CountryName,CountryCode,IndicatorName,IndicatorCode,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,4.044021,2.883604,3.315247,3.656365,2.529129,3.397787,...,0.627472,-2.372065,0.421441,0.474764,-0.931196,-1.028282,3.626041,4.257462,NaN,NaN
2,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,12.686269,...,6.441213,7.385772,4.673996,-0.661709,4.383892,4.975952,0.626149,2.302373,NaN,NaN
6,Andorra,AND,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United Arab Emirates,ARE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.662269,1.101118,2.346269,4.069966,1.617488,1.966826,3.068634,-1.931081,-2.079403,NaN
9,Argentina,ARG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,British Virgin Islands,VGB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,Virgin Islands (U.S.),VIR,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,Kosovo,XKX,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,-1.084813,-1.064727,-1.385189,...,2.476738,1.767324,0.428958,-0.536929,0.273169,1.488234,1.053798,2.675992,0.198228,3.353691
262,"Yemen, Rep.",YEM,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,4.590000,11.911591,12.238534,10.832361,12.515095,11.811264,...,9.885387,10.968442,8.104726,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,Zimbabwe,ZWE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.725327,1.634950,-0.197785,-2.430968,-1.543670,0.893962,10.618866,255.304991,557.201817,98.546105

Dropping the missing values:

In [38]:
DF1csv.dropna(inplace=True) 
DF1csv

/var/folders/jb/lq0t13x96m323srfn512c7cm0000gn/T/ipykernel_22863/2938897227.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1csv.dropna(inplace=True)

,CountryName,CountryCode,IndicatorName,IndicatorCode,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,4.918354,2.369193,-2.134006,0.117317,6.318777,-1.379148,...,-1.833977,5.635318,-0.709567,2.885166,1.515938,4.917139,4.738331,0.181216,-18.698325,17.225300
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,0.750996,1.036421,1.265662,0.466080,2.788589,3.361069,...,-1.850848,1.402217,1.182822,0.169095,-0.490755,-0.106816,-0.172927,-0.596607,-5.433164,1.643080
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,0.967465,2.352157,6.931811,2.641242,5.051312,2.928476,...,2.259185,3.256967,3.094595,0.021242,-2.530712,-0.390086,0.269736,0.542605,-3.426405,1.357098
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,-0.234946,0.838227,9.937307,-0.466061,7.127077,11.009566,...,4.536024,1.101887,1.028262,-2.646420,-6.011783,-3.633446,-4.676622,-4.014917,-8.635446,-2.050717
5,Albania,ALB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,7.630022,9.314397,4.850475,5.924212,5.956570,6.067882,...,1.584873,1.187234,1.985388,2.516827,3.480293,3.897741,4.276326,2.523894,-2.925821,9.526027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,World,WLD,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,3.119439,0.665481,0.978952,1.797787,3.156431,2.707026,...,1.452626,1.552279,1.845769,1.861904,1.607853,2.208661,2.158305,1.519283,-4.085362,4.964844
260,Samoa,WSM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,4.066719,6.509151,5.029245,4.757965,2.740298,6.326567,...,-4.593626,-0.801458,-0.247107,2.924962,6.947335,0.387482,-1.591223,3.365467,-4.471685,-8.713424
263,South Africa,ZAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,3.201510,1.794443,2.760878,2.001994,3.581230,4.286772,...,1.044229,1.099462,-0.172221,-0.757928,-0.309171,0.766942,0.285736,-0.987175,-7.481093,3.870315
264,Zambia,ZMB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,1.062292,2.208315,1.360081,3.691828,3.683416,3.741432,...,4.103279,1.676101,1.352928,-0.312861,0.561271,0.331284,0.897347,-1.564237,-5.595733,1.669097
265,Zimbabwe,ZWE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,-4.027576,0.789791,-9.454025,-17.621841,-6.466319,-6.203725,...,13.654750,0.988283,-0.715190,-0.132760,-1.177893,1.974846,2.909395,-8.177320,-9.670405,6.271613

In [39]:
DF2csv.dropna(inplace=True) 
DF2csv

,CountryName,CountryCode,IndicatorName,IndicatorCode,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,20390.000000,20510.000000,19290.000000,21120.000000,24010.000000,20370.000000,...,24440.000000,25500.000000,25790.000000,26180.000000,26650.000000,27720.000000,29030.000000,30000.000000,24590.000000,29390.000000
1,Africa Eastern and Southern,AFE,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,656.176751,629.894844,615.771592,666.312226,810.760703,1015.829058,...,1679.256511,1711.725316,1691.540731,1574.778660,1456.026987,1440.565428,1452.233541,1493.732269,1386.163976,1453.744944
3,Africa Western and Central,AFW,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,452.032442,474.237653,517.338594,578.193287,704.092894,831.636292,...,1763.846950,1923.711925,2096.815123,2004.978658,1771.335338,1587.397582,1604.628244,1663.335667,1644.359873,1707.394011
4,Angola,AGO,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,360.000000,390.000000,590.000000,710.000000,1010.000000,1370.000000,...,4060.000000,4650.000000,4800.000000,3880.000000,2450.000000,1980.000000,1870.000000,2040.000000,1740.000000,1710.000000
5,Albania,ALB,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,1100.000000,1280.000000,1370.000000,1650.000000,2100.000000,2620.000000,...,4360.000000,4540.000000,4540.000000,4390.000000,4320.000000,4290.000000,4860.000000,5230.000000,5260.000000,6110.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,Vanuatu,VUT,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,1370.000000,1320.000000,1180.000000,1310.000000,1530.000000,1710.000000,...,2750.000000,2930.000000,2930.000000,2770.000000,2780.000000,2860.000000,3120.000000,3400.000000,3180.000000,3240.000000
259,World,WLD,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,5494.792997,5470.219809,5424.935410,5819.245473,6631.751657,7344.587260,...,10462.010400,10829.504040,10944.315160,10585.262740,10329.219880,10407.209080,11094.051550,11496.209450,11037.654000,12023.200460
263,South Africa,ZAF,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,3280.000000,3080.000000,2890.000000,3180.000000,4070.000000,5480.000000,...,8320.000000,8050.000000,7340.000000,6550.000000,5960.000000,5950.000000,6390.000000,6730.000000,6090.000000,6530.000000
264,Zambia,ZMB,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,350.000000,360.000000,380.000000,420.000000,480.000000,580.000000,...,1660.000000,1720.000000,1760.000000,1540.000000,1340.000000,1270.000000,1400.000000,1390.000000,1130.000000,1030.000000
265,Zimbabwe,ZWE,"GNI per capita, Atlas method (current US$)",NY.GNP.PCAP.CD,360.000000,390.000000,370.000000,340.000000,320.000000,330.000000,...,1120.000000,1200.000000,1210.000000,1220.000000,1200.000000,1170.000000,1550.000000,1450.000000,1460.000000,1530.000000

In [40]:
DF3csv.dropna(inplace=True) 
DF3csv

,CountryName,CountryCode,IndicatorName,IndicatorCode,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,8.601485,5.840354,8.763754,7.449700,5.023421,8.558038,...,9.158707,5.750981,5.370290,5.250171,6.571396,6.399343,4.720811,4.120246,6.362961,6.079328
3,Africa Western and Central,AFW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2.530775,4.361529,3.188693,1.760904,0.694336,5.631634,...,4.578375,2.439201,1.758052,2.130268,1.494564,1.764635,1.784050,1.758565,2.437609,3.837868
4,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,324.996872,152.561023,108.897436,98.224144,43.542107,22.953514,...,10.277905,8.777814,7.280387,9.353840,30.698958,29.842578,19.630594,17.079704,22.271564,25.754266
5,Albania,ALB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.050018,3.107588,7.770526,0.484003,2.280019,2.366582,...,2.031593,1.937621,1.625865,3.501208,-0.367317,2.060598,2.028060,1.411091,1.620887,2.041472
7,Arab World,ARB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.853790,1.772204,1.832994,2.712592,3.632280,3.493685,...,4.611844,3.238108,2.773516,1.814077,2.068840,1.966826,2.458142,1.091848,1.777408,3.423629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,Vanuatu,VUT,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2.537688,3.577555,1.963568,3.016241,1.418919,1.199201,...,1.347404,1.458934,0.798864,2.483269,0.842069,3.084526,2.330964,2.762520,5.329351,2.343284
259,World,WLD,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,3.433516,3.836573,2.907999,3.025045,3.517999,4.107251,...,3.725327,2.621050,2.346269,1.434318,1.550016,2.192010,2.438737,2.186902,1.920968,3.495058
260,Samoa,WSM,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.966782,3.838285,8.050314,0.115830,16.313151,1.856764,...,2.049019,0.610086,-0.406816,0.724470,1.304719,1.749897,4.197459,0.982327,-1.568912,3.133205
263,South Africa,ZAF,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,5.338951,5.701900,9.494711,5.679418,-0.692030,2.062846,...,5.724658,5.784469,6.129838,4.540642,6.571396,5.184247,4.517165,4.120246,3.210036,4.611672
264,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,26.030412,21.393782,22.233345,21.401578,17.967789,18.324440,...,6.575900,6.977676,7.806876,10.110593,17.869730,6.577312,7.494572,9.150316,15.732585,22.021234

In [41]:
#Verifying if the data in the same columns have an identical datatype:
theZips=zip(DF1csv.dtypes,
            DF2csv.dtypes,
            DF3csv.dtypes)

[x for x in theZips if len(set(x))>1]

[]

In [44]:
#Given that all three dataframes now have columns that have an identical name, location and datatype, 
#we will integrate the dataframes by appending:
inflation=pd.concat([DF1csv,DF2csv,DF3csv])
inflation

,CountryName,CountryCode,IndicatorName,IndicatorCode,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,4.918354,2.369193,-2.134006,0.117317,6.318777,-1.379148,...,-1.833977,5.635318,-0.709567,2.885166,1.515938,4.917139,4.738331,0.181216,-18.698325,17.225300
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,0.750996,1.036421,1.265662,0.466080,2.788589,3.361069,...,-1.850848,1.402217,1.182822,0.169095,-0.490755,-0.106816,-0.172927,-0.596607,-5.433164,1.643080
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,0.967465,2.352157,6.931811,2.641242,5.051312,2.928476,...,2.259185,3.256967,3.094595,0.021242,-2.530712,-0.390086,0.269736,0.542605,-3.426405,1.357098
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,-0.234946,0.838227,9.937307,-0.466061,7.127077,11.009566,...,4.536024,1.101887,1.028262,-2.646420,-6.011783,-3.633446,-4.676622,-4.014917,-8.635446,-2.050717
5,Albania,ALB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,7.630022,9.314397,4.850475,5.924212,5.956570,6.067882,...,1.584873,1.187234,1.985388,2.516827,3.480293,3.897741,4.276326,2.523894,-2.925821,9.526027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,Vanuatu,VUT,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,2.537688,3.577555,1.963568,3.016241,1.418919,1.199201,...,1.347404,1.458934,0.798864,2.483269,0.842069,3.084526,2.330964,2.762520,5.329351,2.343284
259,World,WLD,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,3.433516,3.836573,2.907999,3.025045,3.517999,4.107251,...,3.725327,2.621050,2.346269,1.434318,1.550016,2.192010,2.438737,2.186902,1.920968,3.495058
260,Samoa,WSM,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.966782,3.838285,8.050314,0.115830,16.313151,1.856764,...,2.049019,0.610086,-0.406816,0.724470,1.304719,1.749897,4.197459,0.982327,-1.568912,3.133205
263,South Africa,ZAF,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,5.338951,5.701900,9.494711,5.679418,-0.692030,2.062846,...,5.724658,5.784469,6.129838,4.540642,6.571396,5.184247,4.517165,4.120246,3.210036,4.611672
264,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,26.030412,21.393782,22.233345,21.401578,17.967789,18.324440,...,6.575900,6.977676,7.806876,10.110593,17.869730,6.577312,7.494572,9.150316,15.732585,22.021234